# Generated by Django 2.1.1 on 2018-09-16 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='trigger',
        ),
        migrations.AddField(
            model_name='drinkinggame',
            name='rating',
            field=models.IntegerField(choices=[(1, 'A-cup anime titties'), (2, 'B-cup anime titties'), (3, 'C-cup anime titties'), (4, 'D-cup anime titties'), (5, 'DD-cup anime titties')], default=0),
        ),
        migrations.AddField(
            model_name='trigger',
            name='action',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='trigger',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='drinkinggame',
            name='play_date',
            field=models.DateTimeField(null=True, verbose_name='date last played'),
        ),
        migrations.AlterField(
            model_name='drinkinggame',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 22, 10, 51, 137804), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='trigger',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
