# Generated by Django 2.1.1 on 2018-09-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='trigger',
            new_name='description',
        ),
        migrations.AddField(
            model_name='drinkinggame',
            name='rating',
            field=models.IntegerField(choices=[(1, 'A anime tittie'), (2, 'B anime titties'), (3, 'C anime titties'), (4, 'D anime titties'), (5, 'DD anime titties')], default=0),
        ),
    ]
