# Generated by Django 2.1.1 on 2018-09-15 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots_app', '0002_auto_20180915_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkinggame',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 15, 28, 9, 346876), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='drinkinggame',
            name='rating',
            field=models.IntegerField(choices=[(1, 'A-cup anime titties'), (2, 'B-cup anime titties'), (3, 'C-cup anime titties'), (4, 'D-cup anime titties'), (5, 'DD-cup anime titties')], default=0),
        ),
    ]
