# Generated by Django 2.1.1 on 2018-09-15 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots_app', '0003_auto_20180915_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkinggame',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 15, 32, 40, 326751), verbose_name='date created'),
        ),
    ]
