# Generated by Django 2.1.1 on 2018-09-16 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shots_app', '0003_auto_20180915_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkinggame',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 4, 47, 45, 428372, tzinfo=utc), verbose_name='date created'),
        ),
    ]
