# Generated by Django 2.1.1 on 2018-09-16 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots_app', '0004_auto_20180915_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkinggame',
            name='play_date',
            field=models.DateTimeField(default=None, verbose_name='date last played'),
        ),
        migrations.AlterField(
            model_name='drinkinggame',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 21, 7, 56, 578826), verbose_name='date created'),
        ),
    ]
