# Generated by Django 2.1.1 on 2018-09-16 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots_app', '0005_auto_20180915_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkinggame',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 21, 35, 44, 821839), verbose_name='date created'),
        ),
    ]
